apiVersion: networking.istio.io/v1alpha3
kind: Gateway
metadata:
  annotations:
  name: strimzi-kafka-gw-broker
  namespace: kafka
spec:
  selector:
    istio: ingressgateway
  servers:
  - hosts:
    - myserver
    port:
      name: https
      number: 9094
      protocol: HTTP2
---
apiVersion: networking.istio.io/v1alpha3
kind: Gateway
metadata:
  annotations:
  name: strimzi-kafka-gw-bootstrap
  namespace: kafka
spec:
  selector:
    istio: ingressgateway
  servers:
  - hosts:
    - myserver
    port:
      name: tls-9093
      number: 9093
      protocol: TLS
    tls:
      mode: SIMPLE
      credentialName: myserver-tls
---
apiVersion: networking.istio.io/v1alpha3
kind: VirtualService
metadata:
  annotations:
  name: strimzi-kafka-vs-broker
  namespace: kafka
spec:
  gateways:
  - strimzi-kafka-gw-broker
  hosts:
  - my-server
  http:
  - match:
    - uri:
        prefix: /
    route:
    - destination:
        host: my-cluster-kafka-brokers
        port:
          number: 9092
---
apiVersion: networking.istio.io/v1alpha3
kind: VirtualService
metadata:
  annotations:
  name: strimzi-kafka-vs-bootstrap
  namespace: kafka
spec:
  gateways:
    - strimzi-kafka-gw-bootstrap
  hosts:
    - my-server
  tcp:
    - match:
        - port: 9093
      route:
        - destination:
            host: my-cluster-kafka-bootstrap
            port:
              number: 9092
---
#apiVersion: apps/v1
#kind: Deployment
#metadata:
#  name: consumer
#spec:
#  selector:
#    matchLabels:
#      app: conslsumer
#  template:
#    metadata:
#      labels:
#        app: consumer
#    spec:
#      containers:
#        - name: consumer
#          image: charroux/kafka-consumer
#          resources:
#            requests:
#              memory: 200Mi
#              cpu: 100m
#          ports:
#            - containerPort: 8080
#          env:
#            - name: TOPIC
#              value: my-topic
#            - name: KAFKA_URL
#              value: my-cluster-kafka-bootstrap

